### ISSUE TITLE
Reference frame for SmartServoLIN motions

### ISSUE THREAD

**Issue by sven-hoek** [IFL-CAMP/iiwa_stack#109]
First test of the linear motion worked fine but the problem came up that the topic uses _PoseStamped_ messages without handling the transformation/frame info, it seems. Therefore, the sent pose information needs to be in the iiwa's world frame.
I had a look in the ROS Java code - is there the possibility to access the tf library? Besides, when mounting the robot with a different orientation, the _iiwa_link_0_ differs from the world frame in Sunrise and this orientation needs to be accessible in Java code to handle the transformation correctly.

**Comment by SalvoVirga** [comment]
Up to my knowledge, tf is not natively available in ROSJava.

Anyhow, you are correct, commands both for linear and non linear motions (i.e. publishing onto /iiwa/command/CartesianPose or /iiwa/commands/CartesianPoseLin) are expected to in robot space, i.e. relative to the robot base, `iiwa_link_0`. This is the expected behaviour.

Since you are probably sending those messages from cpp or python ROS nodes, you should be able there to transform any `PoseStamped` messages into robot space before sending them to the robot. There is why they are `PoseStamped` messages, you can work in any reference frame you want as long as before sending a command you transform the pose in the `iiwa_link_0` frame.

As for the position/orientation your specific robot has within your environment, you should specify that in your specific URDF. Your robot may be placed on top of some structure or on a tilted plane and you can generate your own URDF that includes an iiwa URDF linked to the rest of your setup (a table, a cart, the whole room). A pretty old example on how to do that can be found [here](https://github.com/IFL-CAMP/iiwa_stack/wiki/attachtool), it show how to create an URDF that add a tool to the iiwa but the robot is also place on top of a box (upright, but you could change that). You may want to create a MoveIt! package out of that afterwards, that is also a wiki page on that.

In general, you should have your TF tree well defined and consistent to your real setup, then you can manipulate poses the way you need in your code. Just send commands in robot space to the iiwa when needed.

**Comment by SalvoVirga** [comment]
Yes, that is a good solution, you could also define a "fake" tool frame both in your robot model and within Sunrise. When using ROSSmartServo you can select the tool to use via ROS params, so you select that one and everything should work smoothly.
