### ISSUE TITLE
Error while trying to run ROSMonitor

### ISSUE THREAD

**Issue by saunair** [IFL-CAMP/iiwa_stack#76]
The node gets connected to Ros master, later after I try executing the node further I see this error.
![img_1014](https://user-images.githubusercontent.com/9517734/27503100-4059804e-582e-11e7-9ebe-3d840256043d.JPG)

**Comment by SalvoVirga** [comment]
I see, in d2e719db824eecebda2ccbd541372a08faeb47af I removed calls to `SmartServo.validateForImpedanceMode()` from [ROSBaseApplication](https://github.com/SalvoVirga/iiwa_stack/blob/master/iiwa_ros_java/src/de/tum/in/camp/kuka/ros/ROSBaseApplication.java), since that is necessary only when using impedance control and the robot starts in position control.
In ROSMonitor the robot is immediately set to joint impedance control, so that call is necessary there. A fix should be adding it in line 90, I will try to do that on monday.
Thanks for noticing!

**Comment by saunair** [comment]
Great! Thanks for the quick reply.

**Comment by SalvoVirga** [comment]
ROSMonitor doesn't exist anymore after #178 !
